### PR TITLE
Explicitly set arg_seperator

### PR DESCRIPTION
**Pull request by ziegenberg**
We cannot rely on `arg_separator.output` to be set to it's default '&', therefore we explicitly set it here.

Target branch: 11.3.x

- [x] It is a Bug fix
- [ ] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

### CODE REVIEW

**Comment by ziegenberg** [comment]
I added a test.

**Comment by ziegenberg** [comment]
The failing rector tests are probably due to https://github.com/rectorphp/rector/issues/8395.

**Comment by Spomky** [comment]
Thanks. That's a nice addition.
Waiting for CI to pass.

**Comment by Spomky** [comment]
No worries for Rector. I will fix it.

**Comment by ziegenberg** [comment]
I found this while I was working on this: https://tracker.moodle.org/browse/MDL-79678

If we could have a version that includes this fix soon, that would be wonderful.

**Comment by Spomky** [comment]
Excellent. Can you target 11.2? It seems it is more a big fix than a new feature.

**Comment by ziegenberg** [comment]
I'll rebase onto branch 11.2.x and force push. Is that okay with you?

**Comment by ziegenberg** [comment]
Rebased and force-pushed.

**Comment by Spomky** [comment]
Many thanks 👍🏼

**Comment by ziegenberg** [comment]
Many thanks for the quick release! 🎉

**Pull request merged**
