### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by exussum12**
| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #... 
| License       | MIT

Minor changes to use new language features and use pack instead

### CODE REVIEW

**Comment by Spomky** [comment]
Hi @exussum12 ,

Thank you for this PR. Looks good to me.
Can you please fix the minor errors detected during the tests?I will merge it when done.

**Comment by exussum12** [comment]
Its failing the CS check, not sure why (or how part of it are even generated? the cs file doesnt seem to exist)

**Comment by Spomky** [comment]
You are right it seems I need to indicate what to check before submitting a PR.
The error raised during the checks should be more clear.

You can simply do the following:

```sh
get https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer # or with cURL: curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer

chmod a+x php-cs-fixer
./php-cs-fixer fix
rm php-cs-fixer
```

Don't worry if it doesn't pass even with this script; I'll manage that later on.
Many thanks.

**Comment by Spomky** [comment]
Thank you! Merged.
Will be tagged soon.

**Pull request merged**
