### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by CHE1RON**
simple as that

### CODE REVIEW

**Comment by Spomky** [comment]
Hi,

This is not a typo, but the expected method for v11.1

See #166

**Comment by CHE1RON** [comment]
Thanks for letting me know - the text above mentioned `create`, so I guess it was somewhat confusing me 😅

**Comment by Spomky** [comment]
Actually we missed it. The typo is in the text, not the example.

**Comment by CHE1RON** [comment]
Then at least something good came out of it, I guess 😉

**Pull request closed without merging**
