### PR TITLE
Deprecate `::create` API, add `::createFromSecret` and `::generate` APIs

### LINKED ISSUE #165: `OTPInterface::create(null|string $secret = null)` is prone to misuse
### Description

`OTPInterface::create(null|string $secret = null)` API is fundamentally flawed: what happens if the user intention is to create an OTP from a *known* secret, but the variable passed is **unintentionally** `null`?

Factory methods should be splitted by intentions.

### Example

The following solutions are for `TOTP`, but can and should be applied to `HOTP` as well:

```php
interface TOTPInterface extends OTPInterface
{
    /**
     * @param non-empty-string $secret
     */
    public static function createFromSecret(
        string $secret,
        int $period = 30,
        string $digest = 'sha1',
        int $digits = 6
    ): self;

    public static function generate(
        int $period = 30,
        string $digest = 'sha1',
        int $digits = 6
    ): self;
}
```

### PR DESCRIPTION
**Pull request by Slamdunk**
| Q             | A
| ------------- | ---
| Branch?       | `v11`
| Bug fix?      | no
| New feature?  | yes
| Deprecations? | yes
| Tickets       | Fix #165
| License       | MIT

### CODE REVIEW

**Comment by Spomky** [comment]
Excellent. Many thanks.
By the way, I am wondering if it is necessary to have all these optional arguments in the named constructors:

```php
int $period = 30,
string $digest = 'sha1',
int $digits = 6,
int $epoch = 0
```

It could be a good opportunity to refactor here and have explicit setters:

```php
$otp = TOTP::createFromSecret($mySecret) // or ::generate()
    ->withPeriod(42)
    ->withDigits(12)
;
```

Note that the setters already exist (e.g. [here](https://github.com/Spomky-Labs/otphp/blob/v11.0/src/ParameterTrait.php#L174-L194)), but do not return `$this`.
WDYT?

**Comment by Slamdunk** [comment]
> ```
> $otp = TOTP::createFromSecret($mySecret) // or ::generate()
>     ->withPeriod(42)
>     ->withDigits(12)
> ;
> ```

Abolutely yes, but:

> return `$this`.

Absolutely [NO fluent interfaces please](https://ocramius.github.io/blog/fluent-interfaces-are-evil/).
If we aim at that kind of factories, `OTP` should became `@immutable` just like
https://www.php-fig.org/psr/psr-7/#31-psrhttpmessagemessageinterface

That means:

```php
public function withPeriod(int $digits): static
{
    $new = clone $this;
    $new->digits = $digits;

    return $new;
}
```

I can propose a full PR here to:

1. Add all the necessary new methods
2. Deprecate existing ones in favour of the new `with*` variant

And after that you can branch off the new `v12` were I can propose a PR to drop all deprecated methods and add the new magic `@immutable`, see [PSalm](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-immutable) and [PHPStan](https://phpstan.org/writing-php-code/phpdocs-basics#immutable-classes) notes

Ping me if you agree before I start the whole work

**Comment by Spomky** [comment]
What Marco wrote is legit to me.
This is fine and still readable:

```php
$otp = TOTP::createFromSecret($mySecret); // or ::generate()
$otp->setPeriod(42);
$otp->setDigits(12);
```

Keep It Simple. We can just drop the optional parameters from the static methods.

**Comment by Slamdunk** [comment]
Done

**Comment by Spomky** [comment]
Excellent 👌! Many thanks

**Pull request merged**
