### PR TITLE
Add .gitattributes file

### PR DESCRIPTION
**Pull request by vinkla**
[Exclude non-essential files in .gitattributes.](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production)

### CODE REVIEW

**Comment by Spomky** [comment]
That is right that sometimes documentation files or tests are not needed.
If this file is set, all files and directory will be ignored even if they are wanted.
Rather than use these attributes for this project, you should set them in your global configuration.
The same goes for `.gitignore` or other platform specific behaviours.

Please [read this post](http://stackoverflow.com/questions/28026767/where-should-i-place-my-global-gitattributes-file) and especially the accepted answer to know how to configure git attributes globally on your platform and get the same result.

**Comment by vinkla** [comment]
In production these files are useless. They will only take up space.

> If each package maintainer would include a .gitattributes file in which (s)he enumerates all the files and directories that can be excluded from dist, we could have a more clean vendor.

**Comment by Spomky** [comment]
OK. I agree with this point of view.
Before merging this PR, maybe we could add a section in the documentation to explain how to get excluded files and test/read the doc.

**Comment by vinkla** [comment]
:+1: 

Do you want the section in `doc/Use.md` or in `README.md`?

**Comment by Spomky** [comment]
The `README.md` file seems to be the best place (maybe after the [installation section](https://github.com/Spomky-Labs/otphp#installation)).
What do you think?

**Comment by vinkla** [comment]
Done. Added it to the `README.md`. I've also simplified the composer require command. Composer will automagically fetch the latest version when requiring a new package.

**Comment by Spomky** [comment]
Great. Thank you.

**Comment by vinkla** [comment]
Thanks!

**Comment by Spomky** [comment]
Tagged `v6.0.4`

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
