### PR TITLE
use 32 bit compatible pack() format

### LINKED ISSUE #125: 32bit php compat
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 9.1.2

running this library on the latest xampp (inlcuding php 7.3.0) on windows issues the following warning:

```
Warning: pack() [<a href='https://php.net/manual/function.pack'>function.pack</a>]: 64-bit format codes are not available for 32-bit versions of PHP in vendor\spomky-labs\otphp\src\OTP.php on line 128
```

the `pack()` call will return false and this violates the `intToByteString` return-type which makes php hard-error.

### PR DESCRIPTION
**Pull request by staabm**
should fix https://github.com/Spomky-Labs/otphp/issues/125

### CODE REVIEW

**Comment by staabm** [comment]
code inspired by 

https://github.com/kelunik/two-factor/blob/65da89746b2220fa5740a97a1e07799b37d13535/src/Oath.php#L58

**Comment by staabm** [comment]
I was not able to verify thix fix still works for php 64bit, as I dont have it available on my machine. lets see what the unit tests think.

in my 32bit installation at least I can generate OTP values now, which wasn't possible before.

**Comment by Spomky** [comment]
Hi,

Thank your for this PR. 
Can you have a look at #107? It looks like this PR is the reason for this issue.
If it works fine on your 32bits env, I will revert that PR

**Comment by staabm** [comment]
thx for the fast reply. after reverting the change of  #107 it works for me.

**Comment by Spomky** [comment]
Should be fixed in `v9.1.3`.
Feel free to open another issue if there is something wrong with this new release.

**Pull request closed without merging**
